### ISSUE TITLE
Problem with Node created and modified

### ISSUE THREAD

**Issue by gpalleschi** [daniele-athome/jsPlumbTree#4] opened 2020-04-18 08:01 UTC
If I create a node and after I enter to modify it after save it there is this problem :

![image](https://user-images.githubusercontent.com/12493269/79631799-713c3680-815b-11ea-8f96-024cf82ddb9c.png)

This problem happens in every node of the tree.

**Comment by daniele-athome** [comment] 2020-09-11 17:28
Duplicate of #1, reopened.

**Closed by daniele-athome** 2020-09-11 17:28 UTC
Labels: duplicate
